sudo: false

language: cpp

matrix:
    include:
        - os: osx
          compiler: clang
        - os: linux
          dist: trusty
          compiler: gcc
        - os: linux
          dist: precise
          compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - lcov

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install lcov; fi
  - gem install coveralls-lcov

install:
  - mkdir $HOME/install
  - export CARLSIM3_INSTALL_DIR=$HOME/install
  - export CARLSIM3_NO_CUDA=1
  - export CARLSIM3_COVERAGE=1
  - cd external/googletest
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ../../..
  - pwd
  - make -j4
  - make install

script:
  - make test
  - ./carlsim/test/carlsim_tests

after_success:
- lcov -b . -d . -c -o ./coverage.info
- lcov -r coverage.info "/usr*" -o coverage.info
- lcov -r coverage.info "external/*" -o coverage.info
- lcov -r coverage.info "*.h" -o coverage.info
- lcov -r coverage.info "*.cu" -o coverage.info
- coveralls-lcov coverage.info
