sudo: false

language: cpp

matrix:
    include:
      - os: osx
        compiler: clang
      - os: linux
        dist: trusty
        compiler: gcc
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - lcov
      - os: linux
        dist: precise
        compiler: gcc
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - lcov
    fast_finish:
     - true


before_install:
  # Set alias for readability
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then LINUX=true; fi
  - if [[ $LINUX ]]; then gem install coveralls-lcov; fi

install:
  - mkdir $HOME/install
  - export CARLSIM3_INSTALL_DIR=$HOME/install
  - export CARLSIM3_NO_CUDA=1
  - if [[ $LINUX ]]; then export CARLSIM3_COVERAGE=1; fi
  - cd external/googletest
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ../../..
  - pwd
  - make -j4
  - make install

script:
  - make test
  - ./carlsim/test/carlsim_tests

after_success:
- if [[ $LINUX ]]; then lcov -b . -d . -c -o ./coverage.info; fi
- if [[ $LINUX ]]; then lcov -r coverage.info "/usr*" -o coverage.info; fi
- if [[ $LINUX ]]; then lcov -r coverage.info "external/*" -o coverage.info; fi
- if [[ $LINUX ]]; then lcov -r coverage.info "*.h" -o coverage.info; fi
- if [[ $LINUX ]]; then lcov -r coverage.info "*.cu" -o coverage.info; fi
- if [[ $LINUX ]]; then coveralls-lcov coverage.info; fi
