sudo: false

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - lcov
      - ruby

before_install:
  - gem install coveralls-lcov

install:
  - mkdir $HOME/install
  - export CARLSIM3_INSTALL_DIR=$HOME/install
  - export CARLSIM3_CPU_ONLY=1
  - export CARLSIM3_COVERAGE=1
  - cd external/googletest
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ../../..
  - pwd
  - make -j4
  - make install

script:
  - make test
  - ./carlsim/test/carlsim_tests

after_success:
  - lcov --compat-libtool --directory . --capture --output-file coverage.info
  - coveralls-lcov coverage.info
  - coveralls
